<?php

namespace Shop\Models;

/**
 * BaiyangSmsClient
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-19, 08:51:00
 */
class BaiyangSmsClient extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $client_id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $client_name;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $client_code;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $appid;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $secret_key;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $client_state;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $remark;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $create_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $create_at;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $modify_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $modify_at;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_sms_client';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsClient[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsClient
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
