<?php

namespace Shop\Models;

/**
 * BaiyangCpsBigbrandBlacklist
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-19, 10:03:41
 */
class BaiyangCpsBigbrandBlacklist extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $list_id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $phone;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $admin_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $add_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_cps_bigbrand_blacklist';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsBigbrandBlacklist[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsBigbrandBlacklist
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'list_id' => 'list_id',
            'phone' => 'phone',
            'admin_id' => 'admin_id',
            'add_time' => 'add_time'
        );
    }

}
