<?php

namespace Shop\Models;

/**
 * BaiyangSmsProvider
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-19, 08:56:42
 */
class BaiyangSmsProvider extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $provider_id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $provider_name;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $provider_code;

    /**
     *
     * @var double
     * @Column(type="double", length=8, nullable=false)
     */
    public $scale;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $priority;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $provider_state;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $frequency;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $account;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=true)
     */
    public $password;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $access_token;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $remainder_quantity;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $send_quantity;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $reissue_quantity;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $remark;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $create_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $create_at;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $modify_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $modify_at;
    /**
     * @var string 服务商自定义参数
     */
    public $customize;
    /**
     * @var string 下次修改密码的日期
     * @Column(type="dstring",nullable=true)
     */
    public $next_change_password_time;
    /**
     * @var string 是否可自动修改密码
     * @Column(type="integer",length=11,nullable=false)
     */
    public $is_auto_change_password;
    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_sms_provider';
    }


    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsProvider[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsProvider
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
