<?php

namespace Shop\Models;

/**
 * BaiyangCpsReplyUser
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-15, 15:25:49
 */
class BaiyangCpsReplyUser extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $reply_id;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=false)
     */
    public $mobile;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=false)
     */
    public $user_id;

    /**
     *
     * @var string
     * @Column(type="string", length=16, nullable=false)
     */
    public $user_name;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $channel;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $id_card;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $reply_status;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=false)
     */
    public $positive_image;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=false)
     */
    public $opposite_image;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $add_time;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $update_user;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $update_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_cps_reply_user';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsReplyUser[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsReplyUser
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'reply_id' => 'reply_id',
            'mobile' => 'mobile',
            'user_id' => 'user_id',
            'user_name' => 'user_name',
            'channel' => 'channel',
            'id_card' => 'id_card',
            'reply_status' => 'reply_status',
            'positive_image' => 'positive_image',
            'opposite_image' => 'opposite_image',
            'add_time' => 'add_time',
            'update_user' => 'update_user',
            'update_time' => 'update_time'
        );
    }

}
