<?php

namespace Shop\Models;

/**
 * BaiyangSmsProviderPasswords
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-19, 08:58:44
 */
class BaiyangSmsProviderPasswords extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $provider_id;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $old_password;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $new_password;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $modify_type;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $remark;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $create_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $create_at;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_sms_provider_passwords';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsProviderPasswords[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsProviderPasswords
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
