<?php

namespace Shop\Models;

/**
 * BaiyangSmsRecords
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-19, 09:01:48
 */
class BaiyangSmsRecords extends BaseModel
{

    /**
     *
     * @var string
     * @Primary
     * @Identity
     * @Column(type="string", length=20, nullable=false)
     */
    public $record_id;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $provider_code;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $client_code;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ip_address;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $phone;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=true)
     */
    public $session_id;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $user_agent;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $content;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $provider_result;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=true)
     */
    public $is_success;

    /**
     *
     * @var integer
     * @Column(type="integer", length=4, nullable=false)
     */
    public $send_type;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $create_time;
    public $msg_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $create_at;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $modify_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $modify_at;

    public $provider_push_result;

    public $template_code;
    public $remark;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_sms_records';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsRecords[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsRecords
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
