<?php

namespace Shop\Models;

/**
 * BaiyangBusinessMandatary
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-16, 18:34:17
 */
class BaiyangBusinessMandatary extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $mandatary_id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $phone;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $real_name;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $id_card;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=false)
     */
    public $id_card_image;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $business_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=2, nullable=false)
     */
    public $status;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $user_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $update_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_business_mandatary';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangBusinessMandatary[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangBusinessMandatary
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'mandatary_id' => 'mandatary_id',
            'phone' => 'phone',
            'real_name' => 'real_name',
            'id_card' => 'id_card',
            'id_card_image' => 'id_card_image',
            'business_id' => 'business_id',
            'status' => 'status',
            'user_id' => 'user_id',
            'update_time' => 'update_time'
        );
    }

}
