<?php

namespace Shop\Models;

/**
 * BaiyangSmsList
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-19, 08:53:57
 */
class BaiyangSmsList extends BaseModel
{

    /**
     *
     * @var string
     * @Primary
     * @Identity
     * @Column(type="string", length=20, nullable=false)
     */
    public $list_id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $list_type;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $provider_id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $ip_address;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $phone;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $list_info_type;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $remark;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $create_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $create_at;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $modify_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $modify_at;
    /**
     * 过期时间,单位为秒，到期时间=create_time+expire_time
     * @var integer
     * @Column(type="integer",length=11,nullable=true)
     */
    public $expire_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_sms_list';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsList[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangSmsList
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
