<?php

namespace Shop\Models;
use Shop\Models\BaseModel;
/**
 * BaiyangCpsChannel
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-08-25, 17:57:23
 */
class BaiyangCpsChannel extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $channel_id;

    /**
     *
     * @var string
     * @Column(type="string", length=25, nullable=false)
     */
    public $channel_name;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $platform_id;

    /**
     *
     * @var string
     * @Column(type="string", length=80, nullable=false)
     */
    public $title;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $content;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $link;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=false)
     */
    public $logo;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=false)
     */
    public $channel_image;

    /**
     *
     * @var double
     * @Column(type="double", length=5, nullable=false)
     */
    public $back_amount;

    /**
     *
     * @var string
     * @Column(type="string", length=15, nullable=false)
     */
    public $tags;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=false)
     */
    public $condition;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $channel_status;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $creator;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $add_time;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $updater;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $update_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $is_permanent;

    /**
     *
     * @var integer
     * @Column(type="integer", length=8, nullable=false)
     */
    public $expire_day;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $description;

    /**
     *
     * @var double
     * @Column(type="double", length=5, nullable=false)
     */
    public $wap_back_amount;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_cps_channel';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsChannel[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangCpsChannel
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
