<?php

namespace Shop\Models;
use Shop\Models\BaseModel;

/**
 * BaiyangUser
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-09-13, 17:30:11
 */
class BaiyangUser extends BaseModel
{

    /**
     *
     * @var string
     * @Primary
     * @Identity
     * @Column(type="string", length=20, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=false)
     */
    public $username;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=false)
     */
    public $password;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $level;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $money;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $point;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $grow;

    /**
     *
     * @var string
     * @Column(type="string", length=30, nullable=false)
     */
    public $nickname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $sex;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $email;

    /**
     *
     * @var string
     * @Column(type="string", length=15, nullable=false)
     */
    public $phone;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $headimgurl;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=false)
     */
    public $province;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=false)
     */
    public $city;

    /**
     *
     * @var string
     * @Column(type="string", length=10, nullable=false)
     */
    public $county;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $birthday;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $default_consignee;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $pregnancy_status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $date_of_confinement;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $baby_birthday;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $marital_status;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $educational_status;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $occupation;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=false)
     */
    public $monthly_income;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $add_time;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=false)
     */
    public $pay_password;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $balance;

    /**
     *
     * @var double
     * @Column(type="double", length=10, nullable=false)
     */
    public $bonus;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $user_id;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $last_login_time;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $idcard;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $real_name;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=true)
     */
    public $remark;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $app_first_login_time;

    /**
     *
     * @var string
     * @Column(type="string", length=15, nullable=true)
     */
    public $invite_code;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $channel_name;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $app_store;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=true)
     */
    public $pass_user_id;

    /**
     *
     * @var string
     * @Column(type="string", length=100, nullable=true)
     */
    public $union_user_id;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    public $access_token;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    public $unionid;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    public $refresh_token;

    /**
     *
     * @var integer
     * @Column(type="integer", length=6, nullable=true)
     */
    public $expires_in;

    /**
     *
     * @var integer
     * @Column(type="integer", length=2, nullable=true)
     */
    public $subscribe;

    /**
     *
     * @var integer
     * @Column(type="integer", length=8, nullable=true)
     */
    public $old_user_id;

    /**
     *
     * @var string
     * @Column(type="string", length=200, nullable=true)
     */
    public $address_info;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $is_dummy;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $status;

    /**
     *
     * @var string
     * @Column(type="string", nullable=true)
     */
    public $update_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        $this->setup(['notNullValidations'=>false]);
        return 'baiyang_user';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangUser[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangUser
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
