<?php

namespace Shop\Models;

/**
 * BaiyangBusiness
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-16, 18:33:57
 */
class BaiyangBusiness extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $business_id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $phone;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $real_name;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $id_card;

    /**
     *
     * @var integer
     * @Column(type="integer", length=5, nullable=false)
     */
    public $region_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=5, nullable=false)
     */
    public $city_id;

    /**
     *
     * @var string
     * @Column(type="string", length=20, nullable=false)
     */
    public $user_id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $is_del;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $create_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'baiyang_business';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangBusiness[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return BaiyangBusiness
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'business_id' => 'business_id',
            'phone' => 'phone',
            'real_name' => 'real_name',
            'id_card' => 'id_card',
            'region_id' => 'region_id',
            'city_id' => 'city_id',
            'user_id' => 'user_id',
            'is_del' => 'is_del',
            'create_time' => 'create_time'
        );
    }

}
