<?php

namespace Shop\Models;

/**
 * CustomerService
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-22, 15:58:41
 */
class CustomerService extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=10, nullable=false)
     */
    public $customer_id;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=false)
     */
    public $telephone;

    /**
     *
     * @var string
     * @Column(type="string", length=550, nullable=false)
     */
    public $content;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $add_time;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $serv_id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $serv_nickname;

    /**
     *
     * @var string
     * @Column(type="string", length=255, nullable=false)
     */
    public $remark;

    /**
     *
     * @var integer
     * @Column(type="integer", length=3, nullable=false)
     */
    public $adult_state;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $adult_time;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'customer_service';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return CustomerService[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return CustomerService
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'customer_id' => 'customer_id',
            'telephone' => 'telephone',
            'content' => 'content',
            'add_time' => 'add_time',
            'serv_id' => 'serv_id',
            'serv_nickname' => 'serv_nickname',
            'remark' => 'remark',
            'adult_state' => 'adult_state',
            'adult_time' => 'adult_time'
        );
    }

}
