<?php

namespace Shop\Models;

/**
 * Feedback
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-25, 17:53:33
 */
class Feedback extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=8, nullable=false)
     */
    public $msg_id;

    /**
     *
     * @var string
     * @Column(type="string", length=500, nullable=false)
     */
    public $msg_content;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $msg_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=1, nullable=false)
     */
    public $msg_status;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $serv_id;

    /**
     *
     * @var string
     * @Column(type="string", length=50, nullable=true)
     */
    public $serv_nickname;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=false)
     */
    public $adult_time;
	
	public function initialize ()
	{
		parent::initialize();
		$this->setConnectionService('dbWrite');
    }
    
    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'feedback';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Feedback[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Feedback
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'msg_id' => 'msg_id',
            'msg_content' => 'msg_content',
            'msg_time' => 'msg_time',
            'msg_status' => 'msg_status',
            'serv_id' => 'serv_id',
            'serv_nickname' => 'serv_nickname',
            'adult_time' => 'adult_time'
        );
    }

}
