<?php

namespace Shop\Models;

/**
 * PharmacistConsult
 * 
 * @package Shop\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-05-22, 15:59:11
 */
class PharmacistConsult extends BaseModel
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $consult_id;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $user_name;

    /**
     *
     * @var string
     * @Column(type="string", length=1024, nullable=true)
     */
    public $consult_content;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $product_id;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $product_name;

    /**
     *
     * @var string
     * @Column(type="string", length=32, nullable=true)
     */
    public $user_phone;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $submit_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $finish_time;

    /**
     *
     * @var integer
     * @Column(type="integer", length=2, nullable=true)
     */
    public $consult_status;

    /**
     *
     * @var string
     * @Column(type="string", length=1024, nullable=true)
     */
    public $consult_feedback;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    public $pharmacist_id;

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'pharmacist_consult';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return PharmacistConsult[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return PharmacistConsult
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'consult_id' => 'consult_id',
            'user_name' => 'user_name',
            'consult_content' => 'consult_content',
            'product_id' => 'product_id',
            'product_name' => 'product_name',
            'user_phone' => 'user_phone',
            'submit_time' => 'submit_time',
            'finish_time' => 'finish_time',
            'consult_status' => 'consult_status',
            'consult_feedback' => 'consult_feedback',
            'pharmacist_id' => 'pharmacist_id'
        );
    }

}
